// Communication / notifications port from Code.gs.
import { resolveOrgId } from "../lib/org.js";
import { writeAudit } from "../lib/audit.js";
import { loadViewer, assertStudentAccess } from "../lib/accessScope.js";
import { getImmersiveData } from "./reports.js";

const now = () => new Date().toISOString();
const id = p => `${p}-${Date.now()}-${Math.floor(Math.random()*1000)}`;
function authError(){ return {success:false,error:"Session invalide."}; }
function parse(v,f={}){ if(v && typeof v === "object") return v; try{return JSON.parse(String(v||""));}catch{return f;} }
async function viewerOrNull(env,auth){ return auth?.token ? loadViewer(env,auth) : null; }
async function studentName(env,orgId,sid){ const r=await env.DB.prepare(`SELECT first_name,last_name FROM students WHERE org_id=? AND student_code=? AND deleted_at IS NULL`).bind(orgId,sid).first(); return r ? `${r.first_name||""} ${r.last_name||""}`.trim() : sid; }
async function allowedStudent(env,auth,orgId,sid){ if(!sid)return {allowed:false,error:"Identifiant élève manquant."};const g=await assertStudentAccess(env,auth,orgId,sid);return g.allowed?{allowed:true,student:g.student}:{allowed:false,error:g.error}; }
async function insertGeneric(db,table,orgId,fields,prefix){const rid=id(prefix),t=now();await db.prepare(`INSERT INTO ${table}(id,org_id,fields,version,updated_at,deleted_at) VALUES(?,?,?,1,?,NULL)`).bind(rid,orgId,JSON.stringify(fields),t).run();return {id:rid,updatedAt:t};}
async function queuePushBroadcast(db,orgId,{title,body,audience,gradeLevelId,announcementId,ownerType="parent"}){
  const notificationId=id("PUSH");
  await db.prepare(`INSERT INTO push_notifications(id,org_id,owner_type,owner_id,title,body,data_json,status,created_at,sent_at,error,deleted_at)
    VALUES(?,?,?,?,?,?,?,'QUEUED',?,NULL,NULL,NULL)`)
    .bind(notificationId,orgId,ownerType,"*",title,body,JSON.stringify({channel:"PUSH",audience,gradeLevelId:gradeLevelId||"",announcementId}),now()).run();
  return notificationId;
}
async function queuePushForOwner(db,orgId,{ownerType,ownerId,title,body,data={}}){
  const notificationId=id("PUSH");
  await db.prepare(`INSERT INTO push_notifications(id,org_id,owner_type,owner_id,title,body,data_json,status,created_at,sent_at,error,deleted_at)
    VALUES(?,?,?,?,?,?,?,'QUEUED',?,NULL,NULL,NULL)`)
    .bind(notificationId,orgId,ownerType,ownerId,title,body,JSON.stringify({channel:"PUSH",...data}),now()).run();
  return notificationId;
}

export async function publishAnnouncement(data,auth,env){if(!auth?.token)return authError();try{const title=String(data?.title||"").trim(),body=String(data?.message||data?.body||"").trim();if(!body)return {success:false,error:"Le message ne peut pas être vide."};const audience=String(data?.audience||"ALL").trim()||"ALL",scoped=["CLASS","PARENTS_CLASS"].includes(audience),gradeLevelId=scoped?String(data?.gradeLevelId||data?.classId||"").trim():"";if(scoped&&!gradeLevelId)return {success:false,error:"Classe requise pour cette audience."};const v=await viewerOrNull(env,auth),orgId=await resolveOrgId(env),r=await insertGeneric(env.DB,"announcements",orgId,{title,body,audience,gradeLevelId,channel:"PUSH",authorEmail:v?.email||"",authorName:v?.name||v?.email||"Administration",createdAt:now(),active:true},"ANN");const pushId=await queuePushBroadcast(env.DB,orgId,{title,body,audience,gradeLevelId,announcementId:r.id});await writeAudit(env.DB,{table:"announcements",rowId:r.id,userId:v?.id||null,op:"insert",diff:{audience,gradeLevelId,title,channel:"PUSH",pushId}});return {success:true,id:r.id,pushId,channel:"PUSH"};}catch(e){return {success:false,error:e.message};}}
export async function getAnnouncementsForStudent(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.id||"").trim(),g=await allowedStudent(env,auth,orgId,sid);if(!g.allowed)return {success:false,error:g.error};const level=String(g.student?.current_level||g.student?.CurrentLevel||"").trim(),{results}=await env.DB.prepare(`SELECT id,fields FROM announcements WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at DESC`).bind(orgId).all();const items=(results||[]).map(r=>({r,f:parse(r.fields,{})})).filter(x=>x.f.active!==false&&(String(x.f.audience||"ALL")==="ALL"||String(x.f.gradeLevelId||"")===level)).map(x=>({id:x.r.id,title:x.f.title||"",body:x.f.body||"",author:x.f.authorName||"",createdAt:x.f.createdAt||""}));return {success:true,items};}catch(e){return {success:false,error:e.message};}}
export async function getAnnouncementsList(_data,_auth,env){try{const orgId=await resolveOrgId(env),{results}=await env.DB.prepare(`SELECT id,fields FROM announcements WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at DESC`).bind(orgId).all();return {success:true,items:(results||[]).map(r=>{const f=parse(r.fields,{});return {id:r.id,title:f.title||"",body:f.body||"",audience:f.audience||"ALL",gradeLevelId:f.gradeLevelId||"",author:f.authorName||"",createdAt:f.createdAt||"",active:f.active!==false};})};}catch(e){return {success:false,error:e.message};}}
export async function deleteAnnouncement(data,auth,env){try{const orgId=await resolveOrgId(env),rid=String(data?.id||"").trim();if(!rid)return {success:false,error:"Identifiant manquant."};const v=await viewerOrNull(env,auth),r=await env.DB.prepare(`UPDATE announcements SET deleted_at=?,updated_at=?,version=version+1 WHERE id=? AND org_id=? AND deleted_at IS NULL`).bind(now(),now(),rid,orgId).run();if(!r.meta?.changes)return {success:false,error:"Annonce introuvable."};await writeAudit(env.DB,{table:"announcements",rowId:rid,userId:v?.id||null,op:"delete",diff:{}});return {success:true};}catch(e){return {success:false,error:e.message};}}
export async function reportSecurityIncident(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.target||"").trim(),v=await viewerOrNull(env,auth);let rid="";if(sid){const name=await studentName(env,orgId,sid),g=await env.DB.prepare(`SELECT id,history_id,grade_level_id FROM student_history WHERE org_id=? AND student_id=? AND status='ACTIVE' ORDER BY updated_at DESC LIMIT 1`).bind(orgId,sid).first(),r=await insertGeneric(env.DB,"incidents",orgId,{studentId:sid,studentName:name,historyId:g?.history_id||"",gradeLevelId:g?.grade_level_id||"",type:String(data?.type||"Incident").trim(),severity:String(data?.severity||"Normale").trim(),description:String(data?.description||data?.message||"").trim(),reportedByEmail:v?.email||"",reportedByName:v?.name||v?.email||"Staff",createdAt:now(),status:"OPEN"},"INC");rid=r.id;}await writeAudit(env.DB,{table:"incidents",rowId:rid||String(data?.target||"UNKNOWN"),userId:v?.id||null,op:"incident",diff:{target:data?.target||sid,type:data?.type||"Incident"}});return {success:true};}catch(e){await writeAudit(env.DB,{table:"incidents",rowId:String(data?.target||"UNKNOWN"),userId:null,op:"incident_error",diff:{error:e.message}}).catch(()=>{});return {success:true};}}
export async function getStudentIncidents(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.id||"").trim(),g=await allowedStudent(env,auth,orgId,sid);if(!g.allowed)return {success:false,error:g.error};const {results}=await env.DB.prepare(`SELECT id,fields FROM incidents WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at DESC`).bind(orgId).all();return {success:true,items:(results||[]).map(r=>({r,f:parse(r.fields,{})})).filter(x=>String(x.f.studentId||"")===sid).map(x=>({id:x.r.id,type:x.f.type||"",severity:x.f.severity||"",description:x.f.description||"",reportedBy:x.f.reportedByName||"",createdAt:x.f.createdAt||"",status:x.f.status||""}))};}catch(e){return {success:false,error:e.message};}}
export async function getIncidentsForStudent(data,auth,env){return getStudentIncidents(data,auth,env);}
export async function getIncidentsList(_data,_auth,env){try{const orgId=await resolveOrgId(env),{results}=await env.DB.prepare(`SELECT id,fields FROM incidents WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at DESC`).bind(orgId).all();return {success:true,items:(results||[]).map(r=>{const f=parse(r.fields,{});return {id:r.id,studentId:f.studentId||"",studentName:f.studentName||"",type:f.type||"",severity:f.severity||"",description:f.description||"",reportedBy:f.reportedByName||"",createdAt:f.createdAt||"",status:f.status||""};})};}catch(e){return {success:false,error:e.message};}}
async function parentReplyDefault(env){const r=await env.DB.prepare(`SELECT value FROM settings WHERE key='PARENT_PORTAL_ALLOW_REPLY_DEFAULT'`).first();return String(r?.value||"").trim().toUpperCase()!=="FALSE";}
async function replyOverride(env,orgId,sid){const r=await env.DB.prepare(`SELECT can_reply FROM parent_msg_perms WHERE org_id=? AND student_id=? AND deleted_at IS NULL`).bind(orgId,sid).first();return r?Number(r.can_reply)!==0:null;}
export async function sendMessageToAdmin(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.id||"").trim(),g=await allowedStudent(env,auth,orgId,sid);if(!g.allowed)return {success:false,error:g.error};const body=String(data?.body||data?.message||"").trim(),audioData=String(data?.audioData||"").trim(),audioMime=String(data?.audioMime||"audio/webm").trim();if(!body&&!audioData)return {success:false,error:"Le message ne peut pas être vide."};if(audioData.length>1500000)return {success:false,error:"Message audio trop volumineux. Maximum: 1,5 Mo."};if(audioData&&!/^data:audio\/(webm|ogg|mp4|mpeg|wav);base64,/i.test(audioData))return {success:false,error:"Format audio non pris en charge."};const can=await replyOverride(env,orgId,sid);if(can===false)return {success:false,error:"Les réponses ne sont pas activées par l'administration pour ce compte."};const v=await viewerOrNull(env,auth),threadId=String(data?.threadId||"").trim()||`THR-${sid}-${Date.now()}`,r=await insertGeneric(env.DB,"sp_messages",orgId,{threadId,studentId:sid,studentName:await studentName(env,orgId,sid),subject:String(data?.subject||"").trim()||"(Sans objet)",body,audioData,audioMime,direction:"OUT",channel:"PUSH",authorRole:"student",authorName:v?.name||v?.email||sid,createdAt:now(),status:"UNREAD"},"MSG");await queuePushBroadcast(env.DB,orgId,{title:audioData?"Nouveau message vocal":"Nouveau message à l'administration",body:body||"Message vocal",audience:"ADMIN",ownerType:"staff",announcementId:r.id});await writeAudit(env.DB,{table:"sp_messages",rowId:r.id,userId:v?.id||null,op:"insert",diff:{studentId:sid,threadId,channel:"PUSH",hasAudio:!!audioData}});return {success:true,id:r.id,threadId,channel:"PUSH",hasAudio:!!audioData};}catch(e){return {success:false,error:e.message};}}
export async function getMyAdminMessages(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.id||"").trim(),g=await allowedStudent(env,auth,orgId,sid);if(!g.allowed)return {success:false,error:g.error};const override=await replyOverride(env,orgId,sid),canReply=override!==null?override:await parentReplyDefault(env),{results}=await env.DB.prepare(`SELECT id,fields FROM sp_messages WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at ASC`).bind(orgId).all(),items=(results||[]).map(r=>({r,f:parse(r.fields,{})})).filter(x=>String(x.f.studentId||"")===sid).map(x=>({id:x.r.id,threadId:x.f.threadId||"",subject:x.f.subject||"",body:x.f.body||"",audioData:x.f.audioData||"",audioMime:x.f.audioMime||"",direction:x.f.direction||"",author:x.f.authorName||"",createdAt:x.f.createdAt||"",status:x.f.status||""}));await env.DB.prepare(`UPDATE sp_messages SET fields=json_set(fields,'$.status','READ'),version=version+1,updated_at=? WHERE org_id=? AND deleted_at IS NULL AND json_extract(fields,'$.studentId')=? AND json_extract(fields,'$.direction')='IN' AND json_extract(fields,'$.status')='UNREAD'`).bind(now(),orgId,sid).run().catch(()=>{});return {success:true,items,canReply};}catch(e){return {success:false,error:e.message};}}
export async function getAdminMessagesInbox(_data,_auth,env){try{const orgId=await resolveOrgId(env),{results}=await env.DB.prepare(`SELECT id,fields FROM sp_messages WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at ASC`).bind(orgId).all(),threads={};for(const r of results||[]){const f=parse(r.fields,{}),t=String(f.threadId||"");if(!t)continue;(threads[t]??={threadId:t,studentId:f.studentId||"",studentName:f.studentName||"",messages:[]}).messages.push({id:r.id,subject:f.subject||"",body:f.body||"",direction:f.direction||"",author:f.authorName||"",createdAt:f.createdAt||"",status:f.status||""});}const def=await parentReplyDefault(env),items=Object.values(threads).map(t=>{t.messages.sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));const last=t.messages.at(-1),unread=t.messages.filter(m=>m.direction==='OUT'&&m.status==='UNREAD').length;return {...t,lastSubject:last?.subject||"",lastBody:last?.body||"",lastAt:last?.createdAt||"",unread,canReply:def};});for(const x of items){const o=await replyOverride(env,orgId,String(x.studentId));x.canReply=o!==null?o:def;}items.sort((a,b)=>new Date(b.lastAt)-new Date(a.lastAt));return {success:true,items};}catch(e){return {success:false,error:e.message};}}
export async function replyToAdminMessage(data,auth,env){try{const orgId=await resolveOrgId(env),threadId=String(data?.threadId||"").trim(),body=String(data?.body||data?.message||"").trim();if(!threadId)return {success:false,error:"Fil de discussion manquant."};if(!body)return {success:false,error:"Le message ne peut pas être vide."};const row=await env.DB.prepare(`SELECT fields FROM sp_messages WHERE org_id=? AND deleted_at IS NULL AND json_extract(fields,'$.threadId')=? ORDER BY updated_at ASC LIMIT 1`).bind(orgId,threadId).first();if(!row)return {success:false,error:"Conversation introuvable."};const f=parse(row.fields,{}),v=await viewerOrNull(env,auth),r=await insertGeneric(env.DB,"sp_messages",orgId,{threadId,studentId:f.studentId||"",studentName:f.studentName||"",subject:"(Réponse)",body,direction:"IN",authorRole:"admin",authorName:v?.name||v?.email||"Administration",createdAt:now(),status:"UNREAD"},"MSG");await queuePushBroadcast(env.DB,orgId,{title:"Réponse de l'administration",body,audience:"PARENT",announcementId:r.id});await env.DB.prepare(`UPDATE sp_messages SET fields=json_set(fields,'$.status','READ'),version=version+1,updated_at=? WHERE org_id=? AND deleted_at IS NULL AND json_extract(fields,'$.threadId')=? AND json_extract(fields,'$.direction')='OUT' AND json_extract(fields,'$.status')='UNREAD'`).bind(now(),orgId,threadId).run();await writeAudit(env.DB,{table:"sp_messages",rowId:r.id,userId:v?.id||null,op:"reply",diff:{threadId}});return {success:true,id:r.id,channel:"PUSH"};}catch(e){return {success:false,error:e.message};}}
export async function setParentReplyPermission(data,auth,env){try{const orgId=await resolveOrgId(env),sid=String(data?.studentId||data?.id||"").trim();if(!sid)return {success:false,error:"Identifiant élève manquant."};const allow=data?.allow!==false,v=await viewerOrNull(env,auth),t=now(),existing=await env.DB.prepare(`SELECT id FROM parent_msg_perms WHERE org_id=? AND student_id=? AND deleted_at IS NULL`).bind(orgId,sid).first();if(existing)await env.DB.prepare(`UPDATE parent_msg_perms SET can_reply=?,updated_by=?,updated_at=? WHERE id=?`).bind(allow?1:0,v?.name||v?.email||"",t,existing.id).run();else await env.DB.prepare(`INSERT INTO parent_msg_perms(id,org_id,student_id,can_reply,updated_by,updated_at,deleted_at) VALUES(?,?,?,?,?,?,NULL)`).bind(id("PMP"),orgId,sid,allow?1:0,v?.name||v?.email||"",t).run();await writeAudit(env.DB,{table:"parent_msg_perms",rowId:sid,userId:v?.id||null,op:"update",diff:{allow}});return {success:true,studentId:sid,canReply:allow};}catch(e){return {success:false,error:e.message};}}
export async function sendInternalMessage(data,auth,env){try{const orgId=await resolveOrgId(env),body=String(data?.text||data?.body||data?.message||"").trim();if(!body)return {success:false,error:"Le message ne peut pas être vide."};const v=await viewerOrNull(env,auth),pushId=await queuePushBroadcast(env.DB,orgId,{title:String(data?.title||"Message interne").trim(),body,audience:"STAFF",ownerType:"staff",announcementId:String(data?.thread||"")});await writeAudit(env.DB,{table:"sp_messages",rowId:String(data?.thread||pushId),userId:v?.id||null,op:"message",diff:{text:body,channel:"PUSH",pushId}});return {success:true,channel:"PUSH",pushId};}catch(e){return {success:false,error:e.message};}}

export async function sendStudentReportEmail(params,auth,env){
  try{
    const sid=String(params?.studentId||params?.studentCode||params?.id||'').trim();
    const org=await resolveOrgId(env);
    const guard=await allowedStudent(env,auth,org,sid);
    if(!guard.allowed)return {success:false,error:guard.error};
    const v=await viewerOrNull(env,auth);
    if(!v)return authError();
    const imm=await getImmersiveData({id:sid},auth,env);
    if(!imm?.success)throw new Error('Données indisponibles.');
    const parent=await env.DB.prepare(`SELECT pa.id,pa.display_name FROM parent_accounts pa JOIN parent_students ps ON ps.parent_id=pa.id AND ps.org_id=pa.org_id WHERE pa.org_id=? AND ps.student_id=? AND pa.deleted_at IS NULL AND ps.deleted_at IS NULL AND pa.active=1 LIMIT 1`).bind(org,sid).first();
    if(!parent)return {success:false,error:'Aucun compte parent actif associé à cet élève.'};
    const title=`Bilan académique : ${imm.studentName||sid}`;
    const body=`${imm.studentName||sid}\nMoyenne : ${imm.finalYearlyAvg}/100\nDécision : ${imm.decision}`;
    const pushId=await queuePushForOwner(env.DB,org,{ownerType:'parent',ownerId:parent.id,title,body,data:{studentId:sid,kind:'ACADEMIC_REPORT'}});
    await writeAudit(env.DB,{table:'communications',rowId:sid,userId:v.id||null,op:'STUDENT_REPORT_PUSH',diff:{channel:'PUSH',pushId,parentId:parent.id}});
    return {success:true,channel:'PUSH',pushId,parentId:parent.id};
  }catch(e){return {success:false,error:e.message};}
}
