import { resolveOrgId } from '../lib/org.js';
import { loadViewer, assertStudentAccess } from '../lib/accessScope.js';
import { writeAudit } from '../lib/audit.js';

const now=()=>new Date().toISOString();
const sid=()=>`EX_${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const subid=()=>`ESB_${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const j=(v,d)=>{try{return v?JSON.parse(v):d}catch{return d}};
const csv=v=>Array.isArray(v)?v.map(String):String(v||'').split(',').map(s=>s.trim()).filter(Boolean);
function authErr(){return {success:false,error:'Session invalide.'}}
async function viewer(env,auth){return auth?.token?loadViewer(env,auth):null}
function manage(v){return !!(v&&(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.p_build||v.permissions?.p_review||v.permissions?.p_grades||v.permissions?.pa_save_settings))}
function examObj(r){const s=j(r.settings_json,{}),q=j(r.questions_json,[]);return {id:r.id,title:r.title||'',subject:r.subject||'',subject_branch:s.subject_branch||'',period:s.period||'',weight:Number(s.weight)||1,description:r.description||'',status:String(r.status||'DRAFT').toUpperCase(),cycle:r.cycle||'',classes:csv(r.classes_csv),students:csv(r.students_csv),settings:s,questions:q,createdBy:r.created_by||'',createdAt:r.created_at||'',updatedAt:r.updated_at||''}}
async function exams(db,org){const {results}=await db.prepare('SELECT * FROM exams WHERE org_id=? AND deleted_at IS NULL ORDER BY updated_at DESC').bind(org).all();return results||[]}
async function getExamRow(db,org,id){return db.prepare('SELECT * FROM exams WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,id).first()}
function sanitize(ex){const o=JSON.parse(JSON.stringify(ex));(o.questions||[]).forEach(q=>{if(q.options)q.options.forEach(x=>delete x.correct);if(q.type==='boolean')delete q.correct;if(q.type==='short')delete q.acceptedAnswers;if(q.type==='numeric'){delete q.expected;delete q.tolerance}if(q.type==='ordering')q.items=[...(q.items||[])].sort(()=>Math.random()-.5);delete q.explanation});if(o.settings)delete o.settings.password;return o}
function available(ex,info){if(ex.status!=='PUBLISHED')return false;const s=ex.settings||{},n=Date.now();if(s.openAt&&!isNaN(Date.parse(s.openAt))&&n<Date.parse(s.openAt))return false;if(s.dueAt&&!isNaN(Date.parse(s.dueAt))&&n>Date.parse(s.dueAt)&&s.latePolicy==='STRICT')return false;if(ex.classes?.length&&info.classRoom&&!ex.classes.map(String).includes(String(info.classRoom))){if(!(s.students||[]).map(String).includes(String(info.studentId)))return false}return true}
async function studentInfo(env,org,v){const studentId=String(v?.id||v?.userId||'');const r=await env.DB.prepare('SELECT student_code,first_name,last_name,current_level,section FROM students WHERE org_id=? AND deleted_at IS NULL AND (student_code=? OR student_code=? ) LIMIT 1').bind(org,studentId, v?.userId||'').first();return {studentId:String(r?.student_code||studentId),studentName:String(r?`${r.first_name||''} ${r.last_name||''}`.trim():(v?.name||'')),classRoom:String(r?.current_level||'')}}
function auto(q,a){const p=Number(q.points)||0;if(a==null||a==='')return {score:0,max:p,manual:false};if(q.type==='single'||q.type==='image'){const c=(q.options||[]).find(x=>x.correct);return {score:c&&String(c.id)===String(a)?p:0,max:p,manual:false}}if(q.type==='multi'){const A=Array.isArray(a)?a.map(String).sort():[],C=(q.options||[]).filter(x=>x.correct).map(x=>String(x.id)).sort();return {score:C.length&&A.join('|')===C.join('|')?p:0,max:p,manual:false}}if(q.type==='boolean')return {score:(q.correct===a||String(q.correct)===String(a))?p:0,max:p,manual:false};if(q.type==='short'){const A=String(q.acceptedAnswers||'').split('|').map(x=>x.trim()).filter(Boolean),x=String(a);return {score:A.some(y=>q.caseSensitive?y===x:y.toLowerCase()===x.toLowerCase())?p:0,max:p,manual:false}}if(q.type==='numeric'){const v=Number(a),e=Number(q.expected),t=Number(q.tolerance)||0;return {score:Number.isFinite(v)&&Math.abs(v-e)<=t?p:0,max:p,manual:false}}if(q.type==='fill'){const b=(String(q.template||'').match(/\[([^\]]+)\]/g)||[]).map(x=>x.slice(1,-1)),A=Array.isArray(a)?a:[],per=b.length?p/b.length:0;let s=0;b.forEach((z,i)=>{if(z.split('|').some(x=>q.caseSensitive?String(x).trim()===String(A[i]||''):String(x).trim().toLowerCase()===String(A[i]||'').toLowerCase()))s+=per});return {score:Math.round(s*100)/100,max:p,manual:false}}if(q.type==='matching'){const pairs=q.pairs||[],m=a&&typeof a==='object'?a:{},per=p/(pairs.length||1);return {score:Math.round(pairs.reduce((s,x)=>s+(String(m[x.id])===String(x.id)?per:0),0)*100)/100,max:p,manual:false}}if(q.type==='ordering'){const items=q.items||[],A=Array.isArray(a)?a:[];return {score:items.length===A.length&&items.every((x,i)=>String(x.id)===String(A[i]))?p:0,max:p,manual:false}}return {score:0,max:p,manual:true}}
function totals(ex,sub){let a=0,m=0,max=0;const grades=sub.grades||{};for(const q of ex.questions||[]){max+=Number(q.points)||0;const x=(sub.answers||[]).find(y=>String(y.questionId)===String(q.id));const g=auto(q,x?.answer);if(!g.manual)a+=g.score;const ms=grades[q.id]?.manualScore;if(ms!=null&&Number.isFinite(Number(ms)))m+=Number(ms)}return {autoScore:+a.toFixed(2),manualScore:+m.toFixed(2),score:+(a+m).toFixed(2),maxScore:max}}
async function saveSub(db,org,s){await db.prepare(`UPDATE exam_submissions SET student_name=?,attempt=?,started_at=?,submitted_at=?,status=?,answers_json=?,grades_json=?,auto_score=?,manual_score=?,score=?,max_score=?,feedback=?,updated_at=? WHERE org_id=? AND id=?`).bind(s.studentName,s.attempt,s.startedAt,s.submittedAt||null,s.status,JSON.stringify(s.answers||[]),JSON.stringify(s.grades||{}),s.autoScore,s.manualScore,s.score,s.maxScore,s.feedback||'',now(),org,s.id).run()}

export async function saveExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const ex=data?.exam;if(!ex?.title)return {success:false,error:'Title required.'};if(!Array.isArray(ex.questions)||!ex.questions.length)return {success:false,error:'At least 1 question required.'};const org=await resolveOrgId(env),id=String(ex.id||sid()),ts=now(),existing=await getExamRow(env.DB,org,id);const created=existing?.created_at||ts;await env.DB.prepare(`INSERT INTO exams(id,org_id,title,subject,description,status,cycle,classes_csv,students_csv,settings_json,questions_json,created_by,created_at,updated_at,version,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,NULL) ON CONFLICT(id) DO UPDATE SET title=excluded.title,subject=excluded.subject,description=excluded.description,status=excluded.status,cycle=excluded.cycle,classes_csv=excluded.classes_csv,students_csv=excluded.students_csv,settings_json=excluded.settings_json,questions_json=excluded.questions_json,updated_at=excluded.updated_at,version=exams.version+1,deleted_at=NULL`).bind(id,org,String(ex.title),String(ex.subject||''),String(ex.description||''),String(ex.status||'DRAFT').toUpperCase(),String(ex.cycle||''),csv(ex.classes).join(','),csv(ex.students||ex.settings?.students).join(','),JSON.stringify(ex.settings||{}),JSON.stringify(ex.questions),String(ex.createdBy||v.id||''),created,ts).run();await writeAudit(env.DB,{table:'exams',rowId:id,userId:v.id,op:existing?'update':'insert',diff:{status:ex.status,qcount:ex.questions.length}});return {success:true,exam:examObj(await getExamRow(env.DB,org,id))}}
export async function listExams(_d,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),rows=await exams(env.DB,org),counts=await env.DB.prepare('SELECT exam_id,COUNT(*) count FROM exam_submissions WHERE org_id=? GROUP BY exam_id').bind(org).all();const m=Object.fromEntries((counts.results||[]).map(x=>[x.exam_id,Number(x.count)]));const out=rows.map(r=>({...examObj(r),submissionsCount:m[r.id]||0}));return {success:true,data:out,exams:out}}
export async function getExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),r=await getExamRow(env.DB,org,data?.examId);return r?{success:true,exam:examObj(r)}:{success:false,error:'Not found.'}}
export async function deleteExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),id=String(data?.examId||''),r=await getExamRow(env.DB,org,id);if(!r)return {success:false,error:'Not found.'};const ts=now();await env.DB.prepare('UPDATE exams SET deleted_at=?,updated_at=?,version=version+1 WHERE org_id=? AND id=?').bind(ts,ts,org,id).run();await writeAudit(env.DB,{table:'exams',rowId:id,userId:v.id,op:'delete',diff:{}});return {success:true}}
export async function publishExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),id=String(data?.examId||''),status=['DRAFT','PUBLISHED','CLOSED'].includes(String(data?.status||'PUBLISHED').toUpperCase())?String(data?.status||'PUBLISHED').toUpperCase():'PUBLISHED';if(!await getExamRow(env.DB,org,id))return {success:false,error:'Not found.'};await env.DB.prepare('UPDATE exams SET status=?,updated_at=?,version=version+1 WHERE org_id=? AND id=?').bind(status,now(),org,id).run();return {success:true,status}}
export async function listExamSubmissions(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),{results}=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND exam_id=? ORDER BY COALESCE(submitted_at,started_at) DESC').bind(org,String(data?.examId||'')).all();const rows=(results||[]).map(subObj);return {success:true,rows,submissions:rows}}
function subObj(r){return {id:r.id,examId:r.exam_id,studentId:r.student_id,studentName:r.student_name||'',attempt:Number(r.attempt)||1,startedAt:r.started_at||'',submittedAt:r.submitted_at||'',status:r.status||'',answers:j(r.answers_json,[]),grades:j(r.grades_json,{}),autoScore:r.auto_score==null?null:Number(r.auto_score),manualScore:r.manual_score==null?null:Number(r.manual_score),score:r.score==null?null:Number(r.score),maxScore:r.max_score==null?null:Number(r.max_score),feedback:r.feedback||''}}
export async function getExamSubmission(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),r=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND id=?').bind(org,data?.submissionId).first();if(!r)return {success:false,error:'Not found.'};const ex=await getExamRow(env.DB,org,r.exam_id);return {success:true,data:{exam:ex?examObj(ex):null,submission:subObj(r),answers:j(r.answers_json,[])}}}
export async function gradeExamSubmission(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(!manage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),r=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND id=?').bind(org,data?.submissionId).first();if(!r)return {success:false,error:'Not found.'};const er=await getExamRow(env.DB,org,r.exam_id);if(!er)return {success:false,error:'Exam not found.'};const ex=examObj(er),s=subObj(r);s.grades=s.grades||{};(data.grades||[]).forEach(g=>{if(g?.questionId){s.grades[g.questionId]=s.grades[g.questionId]||{};if(g.manualScore!=null)s.grades[g.questionId].manualScore=Number(g.manualScore)||0;if(g.feedback!=null)s.grades[g.questionId].feedback=String(g.feedback)}});const t=totals(ex,s);Object.assign(s,t,{status:'GRADED'});await saveSub(env.DB,org,s);return {success:true,score:s.score,maxScore:s.maxScore}}
export async function listStudentExams(_d,auth,env){const v=await viewer(env,auth);if(!v)return authErr();if(String(v.role||'').toUpperCase()!=='STUDENT')return {success:true,exams:[]};const org=await resolveOrgId(env),i=await studentInfo(env,org,v),all=(await exams(env.DB,org)).map(examObj).filter(x=>available(x,i));const {results}=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND student_id=?').bind(org,i.studentId).all();const by={};for(const r of results||[])(by[r.exam_id]??=[]).push(subObj(r));return {success:true,exams:all.map(ex=>{const ss=by[ex.id]||[],last=ss.slice().sort((a,b)=>(b.submittedAt||'').localeCompare(a.submittedAt||''))[0],mx=Number(ex.settings?.retakeMax)||0;return {id:ex.id,title:ex.title,subject:ex.subject,cycle:ex.cycle,settings:{dueAt:ex.settings?.dueAt,timeLimitMin:ex.settings?.timeLimitMin},canTake:!mx||ss.length<mx,attemptsUsed:ss.length,attemptsMax:mx,lastSubmissionStatus:last?`Dernière tentative : ${last.status}${last.score!=null?` (${last.score}/${last.maxScore})`:''}`:''}})}}
export async function startStudentExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();const org=await resolveOrgId(env);const i=await studentInfo(env,org,v);if(!i.studentId)return authErr();const er=await getExamRow(env.DB,org,data?.examId);if(!er)return {success:false,error:'Not found.'};const ex=examObj(er);if(!available(ex,i))return {success:false,error:'Examen non disponible.'};const {results}=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND exam_id=? AND student_id=? ORDER BY attempt').bind(org,ex.id,i.studentId).all();const ss=(results||[]).map(subObj),ip=ss.find(x=>x.status==='IN_PROGRESS');if(ip&&ex.settings?.allowResume!==false){const saved=Object.fromEntries(ip.answers.map(a=>[a.questionId,a.answer]));const rem=ex.settings?.timeLimitMin?Math.max(0,Math.floor(Number(ex.settings.timeLimitMin)*60-(Date.now()-Date.parse(ip.startedAt))/1000)):null;return {success:true,data:{exam:sanitize(ex),submissionId:ip.id,savedAnswers:saved,startedAt:ip.startedAt,remainingSec:rem}}}const mx=Number(ex.settings?.retakeMax)||0;if(mx&&ss.filter(x=>x.status!=='IN_PROGRESS').length>=mx)return {success:false,error:'Nombre de tentatives atteint.'};const s={id:subid(),examId:ex.id,studentId:i.studentId,studentName:i.studentName,attempt:ss.length+1,startedAt:now(),status:'IN_PROGRESS',answers:[],grades:{}};await env.DB.prepare(`INSERT INTO exam_submissions(id,org_id,exam_id,student_id,student_name,attempt,started_at,status,answers_json,grades_json) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(s.id,org,ex.id,s.studentId,s.studentName,s.attempt,s.startedAt,s.status,'[]','{}').run();return {success:true,data:{exam:sanitize(ex),submissionId:s.id,savedAnswers:{},startedAt:s.startedAt,remainingSec:ex.settings?.timeLimitMin?Number(ex.settings.timeLimitMin)*60:null}}}
export async function saveExamProgress(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();const org=await resolveOrgId(env),i=await studentInfo(env,org,v),r=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND id=?').bind(org,data?.submissionId).first();if(!r)return {success:false,error:'Not found.'};if(r.student_id!==i.studentId)return {success:false,error:'Forbidden.'};const s=subObj(r);s.answers=Object.entries(data.answers||{}).map(([questionId,answer])=>({questionId,answer}));await saveSub(env.DB,org,s);return {success:true}}
export async function submitStudentExam(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();const org=await resolveOrgId(env),i=await studentInfo(env,org,v),r=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND id=?').bind(org,data?.submissionId).first();if(!r)return {success:false,error:'Not found.'};if(r.student_id!==i.studentId)return {success:false,error:'Forbidden.'};const er=await getExamRow(env.DB,org,r.exam_id);if(!er)return {success:false,error:'Exam not found.'};const ex=examObj(er),s=subObj(r);s.answers=Object.entries(data.answers||{}).map(([questionId,answer])=>({questionId,answer}));s.submittedAt=now();let penalty=0,st=ex.settings||{};if(st.dueAt&&Date.now()>Date.parse(st.dueAt)){const grace=st.latePolicy==='GRACE_24'&&Date.now()-Date.parse(st.dueAt)<=86400000;if(!grace&&st.latePolicy!=='STRICT')penalty=Math.min(100,Math.ceil((Date.now()-Date.parse(st.dueAt))/86400000)*(Number(st.latePenaltyPct)||0))}const t=totals(ex,s);s.autoScore=t.autoScore;s.maxScore=t.maxScore;let raw=t.score;if(penalty>0)raw=Math.max(0,raw*(1-penalty/100));s.score=+raw.toFixed(2);s.status=ex.questions.some(q=>q.type==='essay'||q.type==='upload')?'PENDING_REVIEW':'GRADED';if(penalty)s.feedback=`Pénalité de retard appliquée : -${penalty}%`;await saveSub(env.DB,org,s);return {success:true,data:{examTitle:ex.title,status:s.status,passed:s.maxScore>0?s.score/s.maxScore*100>=Number(st.passMark||0):false,score:st.scoreVisibility==='IMMEDIATE'&&st.showScore!==false?s.score:null,maxScore:st.scoreVisibility==='IMMEDIATE'&&st.showScore!==false?s.maxScore:null,showScore:st.scoreVisibility==='IMMEDIATE'&&st.showScore!==false,feedback:s.feedback||''}}}
export async function getStudentExamResult(data,auth,env){const v=await viewer(env,auth);if(!v)return authErr();const org=await resolveOrgId(env),i=await studentInfo(env,org,v),{results}=await env.DB.prepare('SELECT * FROM exam_submissions WHERE org_id=? AND exam_id=? AND student_id=? AND status<>?').bind(org,data?.examId,i.studentId,'IN_PROGRESS').all();const ss=(results||[]).map(subObj);if(!ss.length)return {success:false,error:'Aucune tentative finalisée.'};const exr=await getExamRow(env.DB,org,data?.examId);if(!exr)return {success:false,error:'Exam not found.'};const ex=examObj(exr),pol=ex.settings?.retakePolicy||'BEST';let p=pol==='LAST'?ss.slice().sort((a,b)=>(b.submittedAt||'').localeCompare(a.submittedAt||''))[0]:pol==='FIRST'?ss.slice().sort((a,b)=>(a.submittedAt||'').localeCompare(b.submittedAt||''))[0]:pol==='AVG'?{...ss[0],score:+(ss.reduce((x,y)=>x+(y.score||0),0)/ss.length).toFixed(2)}:ss.slice().sort((a,b)=>(b.score||0)-(a.score||0))[0];const set=ex.settings||{};let show=true;if(set.scoreVisibility==='AFTER_DUE')show=!!set.dueAt&&Date.now()>Date.parse(set.dueAt);else if(set.scoreVisibility==='NEVER')show=false;else if(set.scoreVisibility==='MANUAL')show=p.status==='GRADED';return {success:true,data:{examTitle:ex.title,status:p.status,passed:p.maxScore>0?p.score/p.maxScore*100>=Number(set.passMark||0):false,score:show?p.score:null,maxScore:show?p.maxScore:null,showScore:show,feedback:p.feedback||''}}}


// ─────────────────────────────────────────────────────────────────────────────
// Legacy quiz-builder compatibility actions (Code.gs: Exam_Questions)
// These are intentionally separate from the newer exams/exam_submissions model:
// the existing frontend still calls these named actions and expects the old
// {text, options, correct, points, type} question shape.
// ─────────────────────────────────────────────────────────────────────────────
function quizQuestionId() {
  return `QQ_${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
}

export async function addQuizQuestion(data, auth, env) {
  const v = await viewer(env, auth);
  if (!v) return authErr();
  const q = data || {};
  if (!q.exam) return { success:false, error:'Exam requis.' };
  if (!q.text) return { success:false, error:'Question requise.' };
  const options = Array.isArray(q.options) ? q.options : [];
  const id = quizQuestionId();
  const ts = now();
  const org = await resolveOrgId(env);
  await env.DB.prepare(`INSERT INTO quiz_questions
    (id,org_id,exam_title,question_text,option_a,option_b,option_c,option_d,correct_answer,commentary,media_type,media_url,points,question_type,created_by,created_at,updated_at,version,deleted_at)
    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,NULL)`)
    .bind(id,org,String(q.exam),String(q.text),String(options[0] ?? ''),String(options[1] ?? ''),String(options[2] ?? ''),String(options[3] ?? ''),String(q.correct ?? ''),'','','',Number(q.points) || 5,String(q.type || 'mcq'),String(v.id || ''),ts,ts)
    .run();
  await writeAudit(env.DB,{table:'quiz_questions',rowId:id,userId:v.id,op:'insert',diff:{exam:String(q.exam),type:String(q.type||'mcq')}});
  return { success:true };
}

export async function getQuizQuestions(data, auth, env) {
  const v = await viewer(env, auth);
  if (!v) return authErr();
  const examTitle = typeof data === 'string' ? data : String(data?.examTitle || '');
  if (!examTitle) return [];
  const org = await resolveOrgId(env);
  const {results} = await env.DB.prepare(`SELECT question_text,option_a,option_b,option_c,option_d,correct_answer,points,question_type
    FROM quiz_questions WHERE org_id=? AND exam_title=? AND deleted_at IS NULL ORDER BY created_at,id`)
    .bind(org,examTitle.trim()).all();
  return (results || []).map(r => ({
    text:r.question_text,
    options:[r.option_a,r.option_b,r.option_c,r.option_d].filter(x=>x!=='' && x!==null && x!==undefined),
    correct:r.correct_answer,
    points:Number(r.points) || 5,
    type:r.question_type || 'mcq'
  }));
}

export async function updateExamSettings(data, auth, env) {
  // Code.gs stores this under EXAM_SETTINGS_<sanitized ExamTitle> through
  // updateSaaSSettings_. Reproduce that key exactly in D1 settings.
  const v = await viewer(env, auth);
  if (!v) return authErr();
  const payload = data || {};
  const title = String(payload.ExamTitle || '');
  const key = 'EXAM_SETTINGS_' + title.replace(/[^a-z0-9]/gi,'_');
  if (!title) return {success:false,error:'ExamTitle requis.'};
  const ts = now();
  await env.DB.prepare(`INSERT INTO settings(key,value,updated_at) VALUES(?,?,?)
    ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`)
    .bind(key,JSON.stringify(payload),ts).run();
  await writeAudit(env.DB,{table:'settings',rowId:key,userId:v.id,op:'UPDATE_SETTING',diff:{examTitle:title}});
  return {success:true,message:'Sauvegarde : '+key,count:1,duplicatesRemoved:0};
}

export async function getAvailableExams(data, auth, env) {
  const v = await viewer(env, auth);
  if (!v) return authErr();
  const org = await resolveOrgId(env);
  const {results} = await env.DB.prepare(`SELECT DISTINCT subject_id FROM grades
    WHERE org_id=? AND deleted_at IS NULL AND TRIM(COALESCE(subject_id,''))<>'' ORDER BY subject_id`)
    .bind(org).all();
  return (results || []).map(r => ({title:String(r.subject_id || '').trim()}));
}
