import { resolveOrgId } from '../lib/org.js';
import { loadViewer, assertStudentAccess } from '../lib/accessScope.js';
import { writeAudit } from '../lib/audit.js';
const now=()=>new Date().toISOString();
const id=(p)=>`${p}${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,7).toUpperCase()}`;
const csv=v=>Array.isArray(v)?v.map(String):String(v??'').split(',').map(x=>x.trim()).filter(Boolean);
const j=(v,d)=>{try{return v?JSON.parse(v):d}catch{return d}};
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
async function viewer(env,auth){return auth?.token?loadViewer(env,auth):null}
function staffManage(v){return !!(v&&(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.p_review||v.permissions?.p_build||v.permissions?.p_grades||v.permissions?.pa_save_settings))}
function classes(row){return csv(row.classes_csv)}
function mediaObj(r){return {...r,classes:classes(r),tags:csv(r.tags_csv)}}
function hwObj(r){return {...r,classes:classes(r),max_score:num(r.max_score),weight:num(r.weight,1)}}
async function configMax(env,org){
  const r=await env.DB.prepare(`SELECT value FROM settings WHERE key IN ('MAX_SCORE','maxScore','max_score') ORDER BY CASE key WHEN 'MAX_SCORE' THEN 1 WHEN 'maxScore' THEN 2 ELSE 3 END LIMIT 1`).bind().first();
  return num(r?.value,0);
}
export async function saveMedia(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!staffManage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),m=data?.media||data||{},mid=String(m.id||'').trim()||id('MED_'),ts=now();const old=await env.DB.prepare('SELECT created_at FROM media_library WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,mid).first();await env.DB.prepare(`INSERT INTO media_library(id,org_id,title,type,source,url,file_id,mime,size_bytes,thumbnail,cycle,level,classes_csv,subject,description,tags_csv,uploaded_by,created_at,updated_at,version,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,NULL) ON CONFLICT(id) DO UPDATE SET title=excluded.title,type=excluded.type,source=excluded.source,url=excluded.url,file_id=excluded.file_id,mime=excluded.mime,size_bytes=excluded.size_bytes,thumbnail=excluded.thumbnail,cycle=excluded.cycle,level=excluded.level,classes_csv=excluded.classes_csv,subject=excluded.subject,description=excluded.description,tags_csv=excluded.tags_csv,uploaded_by=excluded.uploaded_by,updated_at=excluded.updated_at,version=media_library.version+1,deleted_at=NULL`).bind(mid,org,String(m.title||''),String(m.type||'DOC').toUpperCase(),String(m.source||'URL').toUpperCase(),String(m.url||''),String(m.file_id||m.fileId||''),String(m.mime||''),num(m.size_bytes??m.sizeBytes),String(m.thumbnail||''),String(m.cycle||''),String(m.level||''),csv(m.classes||m.classes_csv).join(','),String(m.subject||''),String(m.description||''),csv(m.tags||m.tags_csv).join(','),String(v.email||v.userId||m.uploaded_by||''),old?.created_at||m.created_at||ts,ts).run();await writeAudit(env.DB,{table:'media_library',rowId:mid,userId:v.id,op:old?'update':'insert',diff:{title:m.title,type:m.type}});return {success:true,ok:true,id:mid}}
export async function listMedia(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};const student=String(v.role||'').toUpperCase()==='STUDENT';if(student&&!((v.permissions||{}).sp_view_documents||(v.permissions||{}).pt_view_bulletin))return {success:true,rows:[]};const org=await resolveOrgId(env);let sql='SELECT * FROM media_library WHERE org_id=? AND deleted_at IS NULL',b=[org];if(data?.cycle){sql+=' AND LOWER(cycle)=LOWER(?)';b.push(String(data.cycle))}if(data?.type){sql+=' AND UPPER(type)=UPPER(?)';b.push(String(data.type))}const {results}=await env.DB.prepare(sql+' ORDER BY created_at DESC').bind(...b).all();let rows=(results||[]).map(mediaObj);let cls=String(data?.className||'').toLowerCase();if(student){const sid=String(v.id||v.userId||'').trim();const sr= sid ? await env.DB.prepare('SELECT current_level FROM students WHERE org_id=? AND student_code=? AND deleted_at IS NULL LIMIT 1').bind(org,sid).first() : null;cls=String(sr?.current_level||v.level||'').toLowerCase();}if(cls)rows=rows.filter(x=>!x.classes.length||x.classes.some(c=>c.toLowerCase()===cls||c.toLowerCase().includes(cls)));return {success:true,rows,data:rows,count:rows.length}}
export async function deleteMedia(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.pa_save_settings))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),mid=String(data?.id||'');if(!mid)return {success:false,error:'id requis'};const r=await env.DB.prepare('SELECT id FROM media_library WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,mid).first();if(!r)return {success:false,error:'Média introuvable'};await env.DB.prepare('UPDATE media_library SET deleted_at=?,updated_at=?,version=version+1 WHERE org_id=? AND id=?').bind(now(),now(),org,mid).run();await writeAudit(env.DB,{table:'media_library',rowId:mid,userId:v.id,op:'delete',diff:{}});return {success:true,ok:true}}
export async function uploadMediaFile(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!staffManage(v))return {success:false,error:'Droits insuffisants.'};if(!data?.contentBase64)return {success:false,error:'contentBase64 requis'};
  // Worker-native replacement for Drive upload: use R2 when configured. No email/Drive dependency.
  if(!env.MEDIA_BUCKET)return {success:false,error:'Stockage média non configuré : ajoutez un binding R2 MEDIA_BUCKET avant les uploads de fichiers.'};
  const raw=String(data.contentBase64).includes(',')?String(data.contentBase64).split(',')[1]:String(data.contentBase64);const bytes=Uint8Array.from(atob(raw),c=>c.charCodeAt(0));const key=`${await resolveOrgId(env)}/${Date.now()}-${String(data.name||'fichier').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,160)}`;await env.MEDIA_BUCKET.put(key,bytes,{httpMetadata:{contentType:String(data.mimeType||'application/octet-stream')}});await writeAudit(env.DB,{table:'media_library',rowId:key,userId:v.id,op:'insert',diff:{upload:true,name:data.name}});return {success:true,ok:true,fileId:key,url:`/media/${encodeURIComponent(key)}`,viewUrl:`/media/${encodeURIComponent(key)}`,size:bytes.byteLength,usedFallback:false}}
export async function saveHomework(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!staffManage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),h=data?.homework||data||{},hid=String(h.id||'').trim()||id('HW_'),ts=now(),old=await env.DB.prepare('SELECT created_at FROM homeworks WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,hid).first();let max=num(h.max_score??h.maxScore);if(!(max>0))max=await configMax(env,org);if(!(max>0))return {success:false,error:'max_score manquant et MAX_SCORE non configuré dans les paramètres.'};await env.DB.prepare(`INSERT INTO homeworks(id,org_id,title,subject,subject_branch,period,cycle,classes_csv,description,due_date,max_score,weight,status,created_by,created_at,updated_at,version,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,NULL) ON CONFLICT(id) DO UPDATE SET title=excluded.title,subject=excluded.subject,subject_branch=excluded.subject_branch,period=excluded.period,cycle=excluded.cycle,classes_csv=excluded.classes_csv,description=excluded.description,due_date=excluded.due_date,max_score=excluded.max_score,weight=excluded.weight,status=excluded.status,updated_at=excluded.updated_at,version=homeworks.version+1,deleted_at=NULL`).bind(hid,org,String(h.title||''),String(h.subject||''),String(h.subject_branch||h.subjectBranch||''),String(h.period||''),String(h.cycle||''),csv(h.classes||h.classes_csv).join(','),String(h.description||''),String(h.due_date||h.dueDate||''),max,num(h.weight,1),String(h.status||'ACTIVE').toUpperCase(),String(v.email||v.userId||''),old?.created_at||h.created_at||ts,ts).run();await writeAudit(env.DB,{table:'homeworks',rowId:hid,userId:v.id,op:old?'update':'insert',diff:{title:h.title,max_score:max}});return {success:true,ok:true,id:hid}}
export async function listHomework(_d,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!staffManage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),{results}=await env.DB.prepare('SELECT * FROM homeworks WHERE org_id=? AND deleted_at IS NULL ORDER BY created_at DESC').bind(org).all();return {success:true,rows:(results||[]).map(hwObj)}}
export async function deleteHomework(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.pa_save_settings))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),hid=String(data?.id||'');if(!hid)return {success:false,error:'id requis'};await env.DB.prepare('UPDATE homeworks SET deleted_at=?,updated_at=?,version=version+1 WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(now(),now(),org,hid).run();return {success:true,ok:true}}
export async function gradeHomework(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.p_review||v.permissions?.pt_edit_grades||v.permissions?.pa_save_settings))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),hid=String(data?.homeworkId||'');const hw=await env.DB.prepare('SELECT * FROM homeworks WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,hid).first();if(!hw)return {success:false,error:'Devoir introuvable'};const grades=Array.isArray(data?.grades)?data.grades:[];if(!grades.length)return {success:false,error:'Aucune note à enregistrer'};const ts=now(),stm=[];for(const g of grades){if(!g?.studentId)continue;const gid=id('HWG_');stm.push(env.DB.prepare(`INSERT INTO homework_grades(id,org_id,homework_id,student_id,student_name,class_name,score,max_score,comment,submitted_at,graded_by,graded_at,version,updated_at,deleted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,1,?,NULL) ON CONFLICT(org_id,homework_id,student_id) DO UPDATE SET student_name=excluded.student_name,class_name=excluded.class_name,score=excluded.score,max_score=excluded.max_score,comment=excluded.comment,graded_by=excluded.graded_by,graded_at=excluded.graded_at,version=homework_grades.version+1,updated_at=excluded.updated_at,deleted_at=NULL`).bind(gid,org,hid,String(g.studentId),String(g.studentName||''),String(g.className||''),num(g.score),num(hw.max_score),String(g.comment||''),g.submitted_at||null,String(v.email||v.userId||''),ts,ts));}if(stm.length)await env.DB.batch(stm);await writeAudit(env.DB,{table:'homework_grades',rowId:hid,userId:v.id,op:'update',diff:{count:stm.length}});return {success:true,ok:true,saved:stm.length}}
export async function getHomeworkGrades(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!staffManage(v))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),{results}=await env.DB.prepare('SELECT * FROM homework_grades WHERE org_id=? AND homework_id=? AND deleted_at IS NULL ORDER BY graded_at DESC').bind(org,String(data?.homeworkId||'')).all();return {success:true,rows:results||[]}}
async function studentIdFor(v,data){return String((v?.role||'').toUpperCase()==='STUDENT'?(v.id||v.userId):(data?.studentId||v?.id||'')).trim()}
export async function listStudentHomework(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};const isStudent=String(v.role||'').toUpperCase()==='STUDENT';if(isStudent&&!((v.permissions||{}).sp_view_homework||(v.permissions||{}).pt_view_exam_calendar||(v.permissions||{}).p_grades))return {success:true,rows:[]};const org=await resolveOrgId(env),studentId=await studentIdFor(v,data);if(!studentId)return {success:false,error:'Élève non identifié'};const guard=await assertStudentAccess(env,auth,org,studentId);if(!guard.allowed && String(v.role||'').toUpperCase()==='STUDENT')return {success:false,error:guard.error};const studentClass=isStudent?String(guard.student?.current_level||'').toLowerCase():String(data?.className||guard.student?.current_level||v.accessScope?.classes?.[0]||'').toLowerCase();const {results}=await env.DB.prepare(`SELECT h.*,g.score,g.comment,g.graded_at FROM homeworks h LEFT JOIN homework_grades g ON g.org_id=h.org_id AND g.homework_id=h.id AND g.student_id=? AND g.deleted_at IS NULL WHERE h.org_id=? AND h.deleted_at IS NULL AND UPPER(h.status) NOT IN ('ARCHIVED','DRAFT') ORDER BY h.due_date DESC`).bind(studentId,org).all();const rows=(results||[]).filter(h=>!studentClass||!h.classes_csv||h.classes_csv.toLowerCase().includes(studentClass)).map(h=>({...hwObj(h),score:h.score==null?null:num(h.score),comment:h.comment||'',graded_at:h.graded_at||'',status:h.score==null?'PENDING':'GRADED'}));return {success:true,rows}}
export async function getStudentHomeworkBulletin(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};const isStudent=String(v.role||'').toUpperCase()==='STUDENT';const resolvedStudentId=await studentIdFor(v,data);const r=await listStudentHomework({...data,studentId:resolvedStudentId},auth,env);if(!r.success)return r;const rows=r.rows.filter(x=>x.status==='GRADED'),sumScore=rows.reduce((a,x)=>a+num(x.score),0),sumMax=rows.reduce((a,x)=>a+num(x.max_score),0),configMax=await configMax(env,await resolveOrgId(env));if(!(configMax>0))return {success:false,error:'MAX_SCORE non configuré dans les paramètres.'};return {success:true,studentId:resolvedStudentId,period:data?.period||'all',rows,totals:{count:rows.length,sumScore,sumMax,averageOnScale:sumMax?Math.round(sumScore/sumMax*configMax*10)/10:0,configMax},generatedAt:now()}}
export async function convertHomeworkToExam(data,auth,env){const v=await viewer(env,auth);if(!v)return {success:false,error:'Session invalide.'};if(!(v.isMaster||v.isGodMode||v.permissions?.pt_build_exam||v.permissions?.p_manual||v.permissions?.pa_save_settings))return {success:false,error:'Droits insuffisants.'};const org=await resolveOrgId(env),hw=await env.DB.prepare('SELECT * FROM homeworks WHERE org_id=? AND id=? AND deleted_at IS NULL').bind(org,String(data?.homeworkId||'')).first();if(!hw)return {success:false,error:'Devoir introuvable'};const exid=id('EX_'),pass=num(data?.passMark);if(!(pass>0))return {success:false,error:'passMark requis pour convertir un devoir en examen.'};const max=num(hw.max_score);const classes=csv(hw.classes_csv);const q={id:id('Q_'),type:'essay',prompt:hw.description||hw.title||'Travail à rendre',points:max,minWords:0,maxWords:0};const ex={id:exid,title:'[Devoir converti] '+hw.title,subject:hw.subject||'',description:hw.description||'',status:'PUBLISHED',cycle:hw.cycle||'',classes,settings:{cycle:hw.cycle||'',classes,dueAt:hw.due_date||'',passMark:pass,retakeMax:0,scoreVisibility:'MANUAL',showScore:false},questions:[q]};const {saveExam}=await import('./exams.js');const res=await saveExam({exam:ex},auth,env);if(!res?.success)return res;await env.DB.prepare('UPDATE homeworks SET status=?,updated_at=?,version=version+1 WHERE org_id=? AND id=?').bind('CONVERTED',now(),org,hw.id).run();return {success:true,ok:true,examId:res.exam?.id||exid,homeworkId:hw.id}}
